### ISSUE TITLE
Type Error while trying to view past scans in 20.8.0

### ISSUE THREAD

**Issue by immauss** [immauss/openvas#10]
This is in the latest version of gvm which is not yet pushed to my github. Documenting here so I can keep track of it. 

Clicking on the link for past scans from the Task list leads to the following error message:

TypeError: Cannot read property 'scan_run_status' of undefined

    in mG
    in tbody
    in t
    in styled.tbody
    in table
    in Unknown
    in t
    in Styled(StripedTable)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in Unknown
    in div
    in Unknown
    in t
    in Layout
    in section
    in tr
    in n
    in div
    in Unknown
    in t
    in Layout
    in n
    in w
    in Unknown
    in n
    in n
    in w
    in withRouter(Connect(n))
    in n
    in Unknown
    in l
    in w
    in Unknown
    in a
    in n
    in Unknown
    in Tg
    in n
    in Unknown
    in w
    in Unknown
    in t
    in t
    in n
    in main
    in t
    in Main
    in Unknown
    in t
    in withLayout(Main)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in withRouter(n)
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in t
    in t
    in Unknown
    in Unknown
    in n
    in w
    in l
    in n
    in n
TypeError: Cannot read property 'scan_run_status' of undefined
    at mG (http://ames:9392/static/js/main.bc743b66.chunk.js:1:1448862)
    at Gi (http://ames:9392/static/js/2.f7d69170.chunk.js:2:684338)
    at bc (http://ames:9392/static/js/2.f7d69170.chunk.js:2:730750)
    at us (http://ames:9392/static/js/2.f7d69170.chunk.js:2:723277)
    at cs (http://ames:9392/static/js/2.f7d69170.chunk.js:2:723202)
    at Zc (http://ames:9392/static/js/2.f7d69170.chunk.js:2:720211)
    at http://ames:9392/static/js/2.f7d69170.chunk.js:2:671596
    at t.unstable_runWithPriority (http://ames:9392/static/js/2.f7d69170.chunk.js:2:747183)
    at Yo (http://ames:9392/static/js/2.f7d69170.chunk.js:2:671305)
    at Vo (http://ames:9392/static/js/2.f7d69170.chunk.js:2:671541)

**Comment by immauss** [comment]
Currently getting this error on all reports. In the container logs I also see:
==> /usr/local/var/log/gvm/gvmd.log <==
md manage:WARNING:2020-09-11 16h10.59 UTC:27508: run_report_format_script: No generate script found at /usr/local/var/lib/gvm/gvmd/report_formats/generate

**Comment by immauss** [comment]
Hmmm seems I missed something in the release notes.... fixing soon.

https://community.greenbone.net/t/reports-are-missing-after-update-to-20-8-0/6572
