### ISSUE TITLE
21.04.09 socker error

### ISSUE THREAD

**Issue by grodriguezl** [immauss/openvas#155]
Hi, version 21.04.09 is breaking.
I'm running `docker run --detach --publish 8084:9392 -e SKIPSYNC=true immauss/openvas:21.04.09`

Will v21.X be supported or should I migrate to v22?

Thanks

```
#######################################
Creating a base DB from /usr/lib/base-db.xz
base data from:
Wed Sep 28 08:42:05 UTC 2022
########################################


NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
Migrating the database to the latest version if needed.
Starting Greenbone Vulnerability Manager...
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
admin
Time to fixup the gvm accounts.
reset
Starting Postfix for report delivery by email
Starting Postfix Mail Transport Agent: postfix.
Starting Open Scanner Protocol daemon for OpenVAS...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ospd/server.py", line 217, in start
    self.server = ThreadedUnixSocketServer(self, str(self.socket_path))
  File "/usr/local/lib/python3.9/dist-packages/ospd/server.py", line 176, in __init__
    super().__init__(address, RequestHandler, bind_and_activate=True)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ospd-openvas", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ospd_openvas/daemon.py", line 1386, in main
    daemon_main('OSPD - openvas', OSPDopenvas)
  File "/usr/local/lib/python3.9/dist-packages/ospd/main.py", line 159, in main
    daemon.init(server)
  File "/usr/local/lib/python3.9/dist-packages/ospd_openvas/daemon.py", line 476, in init
    server.start(self.handle_client_stream)
  File "/usr/local/lib/python3.9/dist-packages/ospd/server.py", line 221, in start
    raise OspdError(
ospd.errors.OspdError: Couldn't bind socket on /var/run/ospd/ospd-openvas.sock. [Errno 98] Address already in use
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ospd/main.py", line 83, in exit_cleanup
    server.close()
  File "/usr/local/lib/python3.9/dist-packages/ospd/server.py", line 231, in close
    super().close()
  File "/usr/local/lib/python3.9/dist-packages/ospd/server.py", line 149, in close
    self.server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
```

**Comment by immauss** [comment]
It looks like something on your host is might already be using the port you are trying to allocate.

"OSError: [Errno 98] Address already in use"

And no. I'm not planning on going any further with 21.04, though if you resolve this issue, it should still work. 

At this point, there's no reason not to upgrade to 22.04. Eventually, probably soon, the scanner in 21.04.09 will start to complain about being too old. 

-Scott
